package buzzword;

/**
 * @author Po Yiu Ho
 */
public enum BuzzWordProperties {
    WORKSPACE_HEADING_LABEL,
    ROOT_BORDERPANE_ID,
    LEFT_TOOLBAR_ID,
    SEGMENTED_BUTTON_BAR,
    FIRST_TOOLBAR_BUTTON,
    LAST_TOOLBAR_BUTTON,

    // WIN/LOSE MESSAGES
    WIN_TITLE,
    WIN_MESSAGE,
    LOSE_TITLE,
    LOSE_MESSAGE,

    HEADING_LABEL;

}